version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hactiv_dashboard
      MYSQL_USER: hactiv_user
      MYSQL_PASSWORD: Gorxlqmdbwj11!@#
    volumes:
      - mysql_data:/var/lib/mysql

  hactiv-web-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - mysql
    environment:
      - KAFKA_BROKERS=kafka:9092
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=hactiv_user
      - DB_PASS=Gorxlqmdbwj11!@#
      - DB_NAME=hactiv_dashboard

  hactiv-web-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - hactiv-web-backend

  hactiv:
    image: hactiv-image
    container_name: HActiV
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/kernel:/sys/kernel:ro
    depends_on:
      - hactiv-web-backend
    environment:
      - BACKEND_URL=http://hactiv-web-backend:8080
    command: sleep infinity

volumes:
  mysql_data:

